version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
  fastapi:
    build:
      context: .
      dockerfile: ./fastapi_app/Dockerfile
    ports:
      - '8001:8000'
    volumes:
      - ./fastapi_app:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
